spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3001/"
            allowedMethods: "*"
            allowedHeaders: "*"

